[[dishes]]
name = "Köttgryta"

[[dishes.ingredients]]
name = "Potatis"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Morötter"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Kålrot"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Buljong"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Öl"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Ris"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Kött"
category = "Misc"
frozen = false
