[[dishes]]
name = "Löksoppa"

[[dishes.ingredients]]
name = "Lök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Riven Ost"
category = "Dairy"
frozen = false

[[dishes.ingredients]]
name = "Stekfläsk"
category = "Protein"
frozen = false

[[dishes.ingredients]]
name = "Vitt Vin"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Baugette"
category = "DryGoods"
frozen = false

[[dishes]]
name = "Spagetti Med Köttfärssås"

[[dishes.ingredients]]
name = "Gul Lök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Vitlök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Gul Lök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Vit Lök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Köttfärs"
category = "Protein"
frozen = false

[[dishes.ingredients]]
name = "Spagetti"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Krossade Tomater"
category = "DryGoods"
frozen = false

[[dishes]]
name = "Chilli Con Carne"

[[dishes.ingredients]]
name = "Chili"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Bönor"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Gul Lök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Vitlök"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Köttfärs"
category = "Protein"
frozen = false

[[dishes.ingredients]]
name = "Svarta Bönor"
category = "Protein"
frozen = false

[[dishes.ingredients]]
name = "Vita Bönor"
category = "Protein"
frozen = false

[[dishes.ingredients]]
name = "Krossade Tomater"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Chorizo"
category = "Protein"
frozen = false

[[dishes]]
name = "Köttgryta"

[[dishes.ingredients]]
name = "Morötter"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Kålrot"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Potatis"
category = "Vegtables"
frozen = false

[[dishes.ingredients]]
name = "Buljong"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Öl"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Ris"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Vitt Vin"
category = "DryGoods"
frozen = false

[[dishes.ingredients]]
name = "Kött"
category = "Misc"
frozen = false

[[dishes.ingredients]]
name = "Beacon"
category = "Misc"
frozen = false
