use std::collections::HashMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize, Eq, PartialOrd, Ord, Copy)]
pub enum Category {
    Vegetables,
    Fruit,
    Dairy,
    Protein,
    Pantry,
    Spices,
    Misc,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Dish {
    pub name: String,
    pub ingredients: Vec<Ingredient>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, PartialOrd)]
pub struct Ingredient {
    pub name: String,
    pub category: Category,
    pub frozen: bool,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Database {
    pub dishes: Vec<Dish>,
}

pub fn ingredient_category_db_eng() -> HashMap<String, Category> {
    HashMap::from([
        // Vegetables
        ("onion".to_string(), Category::Vegetables),
        ("yellow onion".to_string(), Category::Vegetables),
        ("red onion".to_string(), Category::Vegetables),
        ("white onion".to_string(), Category::Vegetables),
        ("green onion".to_string(), Category::Vegetables),
        ("scallion".to_string(), Category::Vegetables),
        ("shallot".to_string(), Category::Vegetables),
        ("shallots".to_string(), Category::Vegetables),
        ("leek".to_string(), Category::Vegetables),
        ("leeks".to_string(), Category::Vegetables),
        ("garlic".to_string(), Category::Vegetables),
        ("garlic clove".to_string(), Category::Vegetables),
        ("garlic cloves".to_string(), Category::Vegetables),
        ("carrot".to_string(), Category::Vegetables),
        ("carrots".to_string(), Category::Vegetables),
        ("potato".to_string(), Category::Vegetables),
        ("potatoes".to_string(), Category::Vegetables),
        ("sweet potato".to_string(), Category::Vegetables),
        ("sweet potatoes".to_string(), Category::Vegetables),
        ("tomato".to_string(), Category::Vegetables),
        ("tomatoes".to_string(), Category::Vegetables),
        ("cherry tomatoes".to_string(), Category::Vegetables),
        ("roma tomatoes".to_string(), Category::Vegetables),
        ("bell pepper".to_string(), Category::Vegetables),
        ("bell peppers".to_string(), Category::Vegetables),
        ("red bell pepper".to_string(), Category::Vegetables),
        ("green bell pepper".to_string(), Category::Vegetables),
        ("yellow bell pepper".to_string(), Category::Vegetables),
        ("cucumber".to_string(), Category::Vegetables),
        ("zucchini".to_string(), Category::Vegetables),
        ("eggplant".to_string(), Category::Vegetables),
        ("broccoli".to_string(), Category::Vegetables),
        ("cauliflower".to_string(), Category::Vegetables),
        ("cabbage".to_string(), Category::Vegetables),
        ("red cabbage".to_string(), Category::Vegetables),
        ("green cabbage".to_string(), Category::Vegetables),
        ("kale".to_string(), Category::Vegetables),
        ("brussels sprouts".to_string(), Category::Vegetables),
        ("spinach".to_string(), Category::Vegetables),
        ("arugula".to_string(), Category::Vegetables),
        ("iceberg lettuce".to_string(), Category::Vegetables),
        ("romaine lettuce".to_string(), Category::Vegetables),
        ("lettuce".to_string(), Category::Vegetables),
        ("celery".to_string(), Category::Vegetables),
        ("celery root".to_string(), Category::Vegetables),
        ("parsnip".to_string(), Category::Vegetables),
        ("turnip".to_string(), Category::Vegetables),
        ("radish".to_string(), Category::Vegetables),
        ("beet".to_string(), Category::Vegetables),
        ("beets".to_string(), Category::Vegetables),
        ("corn".to_string(), Category::Vegetables),
        ("corn on the cob".to_string(), Category::Vegetables),
        ("artichoke".to_string(), Category::Vegetables),
        ("asparagus".to_string(), Category::Vegetables),
        ("fennel".to_string(), Category::Vegetables),
        ("green beans".to_string(), Category::Vegetables),
        ("snap peas".to_string(), Category::Vegetables),
        ("snow peas".to_string(), Category::Vegetables),
        ("peas".to_string(), Category::Vegetables),
        ("avocado".to_string(), Category::Vegetables),
        ("mushroom".to_string(), Category::Vegetables),
        ("mushrooms".to_string(), Category::Vegetables),
        ("button mushrooms".to_string(), Category::Vegetables),
        ("portobello mushrooms".to_string(), Category::Vegetables),
        ("shiitake mushrooms".to_string(), Category::Vegetables),
        ("cremini mushrooms".to_string(), Category::Vegetables),
        ("jalapeno".to_string(), Category::Vegetables),
        ("jalapeño".to_string(), Category::Vegetables),
        ("chili pepper".to_string(), Category::Vegetables),
        ("chili peppers".to_string(), Category::Vegetables),
        ("ginger".to_string(), Category::Vegetables),
        ("fresh ginger".to_string(), Category::Vegetables),
        ("bok choy".to_string(), Category::Vegetables),
        ("napa cabbage".to_string(), Category::Vegetables),
        ("watercress".to_string(), Category::Vegetables),
        ("rutabaga".to_string(), Category::Vegetables),
        ("kohlrabi".to_string(), Category::Vegetables),
        ("collard greens".to_string(), Category::Vegetables),
        ("swiss chard".to_string(), Category::Vegetables),
        // Fruit
        ("apple".to_string(), Category::Fruit),
        ("apples".to_string(), Category::Fruit),
        ("pear".to_string(), Category::Fruit),
        ("pears".to_string(), Category::Fruit),
        ("banana".to_string(), Category::Fruit),
        ("bananas".to_string(), Category::Fruit),
        ("orange".to_string(), Category::Fruit),
        ("oranges".to_string(), Category::Fruit),
        ("lemon".to_string(), Category::Fruit),
        ("lemons".to_string(), Category::Fruit),
        ("lime".to_string(), Category::Fruit),
        ("limes".to_string(), Category::Fruit),
        ("grapefruit".to_string(), Category::Fruit),
        ("mandarin".to_string(), Category::Fruit),
        ("clementine".to_string(), Category::Fruit),
        ("strawberry".to_string(), Category::Fruit),
        ("strawberries".to_string(), Category::Fruit),
        ("raspberry".to_string(), Category::Fruit),
        ("raspberries".to_string(), Category::Fruit),
        ("blueberry".to_string(), Category::Fruit),
        ("blueberries".to_string(), Category::Fruit),
        ("blackberry".to_string(), Category::Fruit),
        ("blackberries".to_string(), Category::Fruit),
        ("cranberry".to_string(), Category::Fruit),
        ("cranberries".to_string(), Category::Fruit),
        ("grapes".to_string(), Category::Fruit),
        ("red grapes".to_string(), Category::Fruit),
        ("green grapes".to_string(), Category::Fruit),
        ("watermelon".to_string(), Category::Fruit),
        ("cantaloupe".to_string(), Category::Fruit),
        ("honeydew".to_string(), Category::Fruit),
        ("mango".to_string(), Category::Fruit),
        ("pineapple".to_string(), Category::Fruit),
        ("papaya".to_string(), Category::Fruit),
        ("kiwi".to_string(), Category::Fruit),
        ("peach".to_string(), Category::Fruit),
        ("peaches".to_string(), Category::Fruit),
        ("nectarine".to_string(), Category::Fruit),
        ("plum".to_string(), Category::Fruit),
        ("plums".to_string(), Category::Fruit),
        ("cherries".to_string(), Category::Fruit),
        ("fig".to_string(), Category::Fruit),
        ("figs".to_string(), Category::Fruit),
        ("dates".to_string(), Category::Fruit),
        ("raisins".to_string(), Category::Fruit),
        ("dried apricots".to_string(), Category::Fruit),
        ("apricot".to_string(), Category::Fruit),
        ("coconut".to_string(), Category::Fruit),
        ("passion fruit".to_string(), Category::Fruit),
        ("pomegranate".to_string(), Category::Fruit),
        ("lychee".to_string(), Category::Fruit),
        // Dairy
        ("milk".to_string(), Category::Dairy),
        ("whole milk".to_string(), Category::Dairy),
        ("skim milk".to_string(), Category::Dairy),
        ("2% milk".to_string(), Category::Dairy),
        ("oat milk".to_string(), Category::Dairy),
        ("almond milk".to_string(), Category::Dairy),
        ("soy milk".to_string(), Category::Dairy),
        ("butter".to_string(), Category::Dairy),
        ("unsalted butter".to_string(), Category::Dairy),
        ("salted butter".to_string(), Category::Dairy),
        ("margarine".to_string(), Category::Dairy),
        ("heavy cream".to_string(), Category::Dairy),
        ("heavy whipping cream".to_string(), Category::Dairy),
        ("half and half".to_string(), Category::Dairy),
        ("sour cream".to_string(), Category::Dairy),
        ("cream cheese".to_string(), Category::Dairy),
        ("yogurt".to_string(), Category::Dairy),
        ("greek yogurt".to_string(), Category::Dairy),
        ("plain yogurt".to_string(), Category::Dairy),
        ("cottage cheese".to_string(), Category::Dairy),
        ("ricotta".to_string(), Category::Dairy),
        ("mascarpone".to_string(), Category::Dairy),
        ("cheese".to_string(), Category::Dairy),
        ("cheddar".to_string(), Category::Dairy),
        ("cheddar cheese".to_string(), Category::Dairy),
        ("gouda".to_string(), Category::Dairy),
        ("swiss cheese".to_string(), Category::Dairy),
        ("parmesan".to_string(), Category::Dairy),
        ("parmesan cheese".to_string(), Category::Dairy),
        ("mozzarella".to_string(), Category::Dairy),
        ("feta".to_string(), Category::Dairy),
        ("feta cheese".to_string(), Category::Dairy),
        ("brie".to_string(), Category::Dairy),
        ("camembert".to_string(), Category::Dairy),
        ("blue cheese".to_string(), Category::Dairy),
        ("gorgonzola".to_string(), Category::Dairy),
        ("halloumi".to_string(), Category::Dairy),
        ("monterey jack".to_string(), Category::Dairy),
        ("pepper jack".to_string(), Category::Dairy),
        ("american cheese".to_string(), Category::Dairy),
        ("provolone".to_string(), Category::Dairy),
        ("gruyere".to_string(), Category::Dairy),
        ("eggs".to_string(), Category::Dairy),
        ("egg".to_string(), Category::Dairy),
        ("egg yolk".to_string(), Category::Dairy),
        ("egg white".to_string(), Category::Dairy),
        ("whipped cream".to_string(), Category::Dairy),
        // Protein
        ("chicken breast".to_string(), Category::Protein),
        ("chicken breasts".to_string(), Category::Protein),
        ("chicken thighs".to_string(), Category::Protein),
        ("chicken legs".to_string(), Category::Protein),
        ("chicken wings".to_string(), Category::Protein),
        ("whole chicken".to_string(), Category::Protein),
        ("ground chicken".to_string(), Category::Protein),
        ("chicken".to_string(), Category::Protein),
        ("ground beef".to_string(), Category::Protein),
        ("beef".to_string(), Category::Protein),
        ("steak".to_string(), Category::Protein),
        ("ribeye".to_string(), Category::Protein),
        ("sirloin".to_string(), Category::Protein),
        ("tenderloin".to_string(), Category::Protein),
        ("brisket".to_string(), Category::Protein),
        ("chuck roast".to_string(), Category::Protein),
        ("short ribs".to_string(), Category::Protein),
        ("beef ribs".to_string(), Category::Protein),
        ("ground pork".to_string(), Category::Protein),
        ("pork".to_string(), Category::Protein),
        ("pork chops".to_string(), Category::Protein),
        ("pork tenderloin".to_string(), Category::Protein),
        ("pork shoulder".to_string(), Category::Protein),
        ("pork belly".to_string(), Category::Protein),
        ("baby back ribs".to_string(), Category::Protein),
        ("spare ribs".to_string(), Category::Protein),
        ("bacon".to_string(), Category::Protein),
        ("ham".to_string(), Category::Protein),
        ("prosciutto".to_string(), Category::Protein),
        ("pancetta".to_string(), Category::Protein),
        ("sausage".to_string(), Category::Protein),
        ("italian sausage".to_string(), Category::Protein),
        ("breakfast sausage".to_string(), Category::Protein),
        ("chorizo".to_string(), Category::Protein),
        ("ground turkey".to_string(), Category::Protein),
        ("turkey".to_string(), Category::Protein),
        ("turkey breast".to_string(), Category::Protein),
        ("ground lamb".to_string(), Category::Protein),
        ("lamb".to_string(), Category::Protein),
        ("lamb chops".to_string(), Category::Protein),
        ("rack of lamb".to_string(), Category::Protein),
        ("leg of lamb".to_string(), Category::Protein),
        ("salmon".to_string(), Category::Protein),
        ("salmon fillet".to_string(), Category::Protein),
        ("smoked salmon".to_string(), Category::Protein),
        ("tuna".to_string(), Category::Protein),
        ("canned tuna".to_string(), Category::Protein),
        ("tilapia".to_string(), Category::Protein),
        ("cod".to_string(), Category::Protein),
        ("halibut".to_string(), Category::Protein),
        ("shrimp".to_string(), Category::Protein),
        ("prawns".to_string(), Category::Protein),
        ("scallops".to_string(), Category::Protein),
        ("crab".to_string(), Category::Protein),
        ("lobster".to_string(), Category::Protein),
        ("clams".to_string(), Category::Protein),
        ("mussels".to_string(), Category::Protein),
        ("tofu".to_string(), Category::Protein),
        ("firm tofu".to_string(), Category::Protein),
        ("silken tofu".to_string(), Category::Protein),
        ("tempeh".to_string(), Category::Protein),
        ("black beans".to_string(), Category::Protein),
        ("kidney beans".to_string(), Category::Protein),
        ("chickpeas".to_string(), Category::Protein),
        ("lentils".to_string(), Category::Protein),
        ("white beans".to_string(), Category::Protein),
        ("pinto beans".to_string(), Category::Protein),
        ("edamame".to_string(), Category::Protein),
        ("hot dogs".to_string(), Category::Protein),
        ("pepperoni".to_string(), Category::Protein),
        ("salami".to_string(), Category::Protein),
        // Pantry
        ("rice".to_string(), Category::Pantry),
        ("white rice".to_string(), Category::Pantry),
        ("brown rice".to_string(), Category::Pantry),
        ("jasmine rice".to_string(), Category::Pantry),
        ("basmati rice".to_string(), Category::Pantry),
        ("pasta".to_string(), Category::Pantry),
        ("spaghetti".to_string(), Category::Pantry),
        ("penne".to_string(), Category::Pantry),
        ("fettuccine".to_string(), Category::Pantry),
        ("rigatoni".to_string(), Category::Pantry),
        ("lasagna noodles".to_string(), Category::Pantry),
        ("egg noodles".to_string(), Category::Pantry),
        ("ramen noodles".to_string(), Category::Pantry),
        ("bread".to_string(), Category::Pantry),
        ("white bread".to_string(), Category::Pantry),
        ("whole wheat bread".to_string(), Category::Pantry),
        ("sourdough".to_string(), Category::Pantry),
        ("baguette".to_string(), Category::Pantry),
        ("tortillas".to_string(), Category::Pantry),
        ("flour tortillas".to_string(), Category::Pantry),
        ("corn tortillas".to_string(), Category::Pantry),
        ("pita bread".to_string(), Category::Pantry),
        ("all-purpose flour".to_string(), Category::Pantry),
        ("flour".to_string(), Category::Pantry),
        ("bread flour".to_string(), Category::Pantry),
        ("whole wheat flour".to_string(), Category::Pantry),
        ("cornmeal".to_string(), Category::Pantry),
        ("oats".to_string(), Category::Pantry),
        ("rolled oats".to_string(), Category::Pantry),
        ("breadcrumbs".to_string(), Category::Pantry),
        ("panko breadcrumbs".to_string(), Category::Pantry),
        ("chicken broth".to_string(), Category::Pantry),
        ("beef broth".to_string(), Category::Pantry),
        ("vegetable broth".to_string(), Category::Pantry),
        ("chicken stock".to_string(), Category::Pantry),
        ("beef stock".to_string(), Category::Pantry),
        ("olive oil".to_string(), Category::Pantry),
        ("vegetable oil".to_string(), Category::Pantry),
        ("canola oil".to_string(), Category::Pantry),
        ("coconut oil".to_string(), Category::Pantry),
        ("sesame oil".to_string(), Category::Pantry),
        ("canned tomatoes".to_string(), Category::Pantry),
        ("diced tomatoes".to_string(), Category::Pantry),
        ("crushed tomatoes".to_string(), Category::Pantry),
        ("tomato paste".to_string(), Category::Pantry),
        ("tomato sauce".to_string(), Category::Pantry),
        ("marinara sauce".to_string(), Category::Pantry),
        ("soy sauce".to_string(), Category::Pantry),
        ("worcestershire sauce".to_string(), Category::Pantry),
        ("hot sauce".to_string(), Category::Pantry),
        ("ketchup".to_string(), Category::Pantry),
        ("mustard".to_string(), Category::Pantry),
        ("dijon mustard".to_string(), Category::Pantry),
        ("mayonnaise".to_string(), Category::Pantry),
        ("vinegar".to_string(), Category::Pantry),
        ("white vinegar".to_string(), Category::Pantry),
        ("apple cider vinegar".to_string(), Category::Pantry),
        ("balsamic vinegar".to_string(), Category::Pantry),
        ("red wine vinegar".to_string(), Category::Pantry),
        ("sugar".to_string(), Category::Pantry),
        ("brown sugar".to_string(), Category::Pantry),
        ("powdered sugar".to_string(), Category::Pantry),
        ("honey".to_string(), Category::Pantry),
        ("maple syrup".to_string(), Category::Pantry),
        ("baking powder".to_string(), Category::Pantry),
        ("baking soda".to_string(), Category::Pantry),
        ("yeast".to_string(), Category::Pantry),
        ("vanilla extract".to_string(), Category::Pantry),
        ("cocoa powder".to_string(), Category::Pantry),
        ("chocolate chips".to_string(), Category::Pantry),
        ("peanut butter".to_string(), Category::Pantry),
        ("almond butter".to_string(), Category::Pantry),
        ("jam".to_string(), Category::Pantry),
        ("jelly".to_string(), Category::Pantry),
        ("salsa".to_string(), Category::Pantry),
        ("coconut milk".to_string(), Category::Pantry),
        ("canned coconut milk".to_string(), Category::Pantry),
        ("fish sauce".to_string(), Category::Pantry),
        ("oyster sauce".to_string(), Category::Pantry),
        ("hoisin sauce".to_string(), Category::Pantry),
        ("sriracha".to_string(), Category::Pantry),
        ("tahini".to_string(), Category::Pantry),
        ("beef bouillon".to_string(), Category::Pantry),
        ("chicken bouillon".to_string(), Category::Pantry),
        ("wine".to_string(), Category::Pantry),
        ("white wine".to_string(), Category::Pantry),
        ("red wine".to_string(), Category::Pantry),
        ("beer".to_string(), Category::Pantry),
        ("almonds".to_string(), Category::Pantry),
        ("walnuts".to_string(), Category::Pantry),
        ("pecans".to_string(), Category::Pantry),
        ("cashews".to_string(), Category::Pantry),
        ("peanuts".to_string(), Category::Pantry),
        ("pine nuts".to_string(), Category::Pantry),
        ("sunflower seeds".to_string(), Category::Pantry),
        ("sesame seeds".to_string(), Category::Pantry),
        ("cornstarch".to_string(), Category::Pantry),
        ("vegetable shortening".to_string(), Category::Pantry),
        ("lard".to_string(), Category::Pantry),
        // Spices
        ("salt".to_string(), Category::Spices),
        ("sea salt".to_string(), Category::Spices),
        ("kosher salt".to_string(), Category::Spices),
        ("black pepper".to_string(), Category::Spices),
        ("white pepper".to_string(), Category::Spices),
        ("red pepper flakes".to_string(), Category::Spices),
        ("cayenne pepper".to_string(), Category::Spices),
        ("paprika".to_string(), Category::Spices),
        ("smoked paprika".to_string(), Category::Spices),
        ("garlic powder".to_string(), Category::Spices),
        ("onion powder".to_string(), Category::Spices),
        ("cumin".to_string(), Category::Spices),
        ("coriander".to_string(), Category::Spices),
        ("turmeric".to_string(), Category::Spices),
        ("cinnamon".to_string(), Category::Spices),
        ("nutmeg".to_string(), Category::Spices),
        ("allspice".to_string(), Category::Spices),
        ("cloves".to_string(), Category::Spices),
        ("cardamom".to_string(), Category::Spices),
        ("ginger powder".to_string(), Category::Spices),
        ("dried ginger".to_string(), Category::Spices),
        ("oregano".to_string(), Category::Spices),
        ("dried oregano".to_string(), Category::Spices),
        ("basil".to_string(), Category::Spices),
        ("dried basil".to_string(), Category::Spices),
        ("thyme".to_string(), Category::Spices),
        ("dried thyme".to_string(), Category::Spices),
        ("rosemary".to_string(), Category::Spices),
        ("dried rosemary".to_string(), Category::Spices),
        ("bay leaves".to_string(), Category::Spices),
        ("parsley".to_string(), Category::Spices),
        ("dried parsley".to_string(), Category::Spices),
        ("fresh parsley".to_string(), Category::Spices),
        ("cilantro".to_string(), Category::Spices),
        ("fresh cilantro".to_string(), Category::Spices),
        ("dill".to_string(), Category::Spices),
        ("fresh dill".to_string(), Category::Spices),
        ("chives".to_string(), Category::Spices),
        ("sage".to_string(), Category::Spices),
        ("dried sage".to_string(), Category::Spices),
        ("tarragon".to_string(), Category::Spices),
        ("marjoram".to_string(), Category::Spices),
        ("chili powder".to_string(), Category::Spices),
        ("italian seasoning".to_string(), Category::Spices),
        ("taco seasoning".to_string(), Category::Spices),
        ("old bay".to_string(), Category::Spices),
        ("everything bagel seasoning".to_string(), Category::Spices),
        ("mustard seeds".to_string(), Category::Spices),
        ("fennel seeds".to_string(), Category::Spices),
        ("caraway seeds".to_string(), Category::Spices),
        ("star anise".to_string(), Category::Spices),
        ("saffron".to_string(), Category::Spices),
        ("vanilla bean".to_string(), Category::Spices),
        ("mint".to_string(), Category::Spices),
        ("fresh mint".to_string(), Category::Spices),
        ("lemongrass".to_string(), Category::Spices),
    ])
}

pub fn ingredient_category_db_swe() -> HashMap<String, Category> {
    HashMap::from([
        // Grönsaker
        ("lök".to_string(), Category::Vegetables),
        ("gul lök".to_string(), Category::Vegetables),
        ("gullök".to_string(), Category::Vegetables),
        ("rödlök".to_string(), Category::Vegetables),
        ("vit lök".to_string(), Category::Vegetables),
        ("vitlök".to_string(), Category::Vegetables),
        ("salladslök".to_string(), Category::Vegetables),
        ("schalottenlök".to_string(), Category::Vegetables),
        ("pärllök".to_string(), Category::Vegetables),
        ("purjolök".to_string(), Category::Vegetables),
        ("vitlöksklyfta".to_string(), Category::Vegetables),
        ("vitlöksklyftor".to_string(), Category::Vegetables),
        ("morot".to_string(), Category::Vegetables),
        ("morötter".to_string(), Category::Vegetables),
        ("potatis".to_string(), Category::Vegetables),
        ("sötpotatis".to_string(), Category::Vegetables),
        ("tomat".to_string(), Category::Vegetables),
        ("tomater".to_string(), Category::Vegetables),
        ("körsbärstomater".to_string(), Category::Vegetables),
        ("plommontomater".to_string(), Category::Vegetables),
        ("paprika".to_string(), Category::Vegetables),
        ("röd paprika".to_string(), Category::Vegetables),
        ("rödpaprika".to_string(), Category::Vegetables),
        ("grön paprika".to_string(), Category::Vegetables),
        ("grönpaprika".to_string(), Category::Vegetables),
        ("gul paprika".to_string(), Category::Vegetables),
        ("gulpaprika".to_string(), Category::Vegetables),
        ("gurka".to_string(), Category::Vegetables),
        ("zucchini".to_string(), Category::Vegetables),
        ("aubergine".to_string(), Category::Vegetables),
        ("broccoli".to_string(), Category::Vegetables),
        ("blomkål".to_string(), Category::Vegetables),
        ("vitkål".to_string(), Category::Vegetables),
        ("kål".to_string(), Category::Vegetables),
        ("rödkål".to_string(), Category::Vegetables),
        ("grönkål".to_string(), Category::Vegetables),
        ("savoykål".to_string(), Category::Vegetables),
        ("brysselkål".to_string(), Category::Vegetables),
        ("spenat".to_string(), Category::Vegetables),
        ("ruccola".to_string(), Category::Vegetables),
        ("isbergssallad".to_string(), Category::Vegetables),
        ("romansallad".to_string(), Category::Vegetables),
        ("sallad".to_string(), Category::Vegetables),
        ("selleri".to_string(), Category::Vegetables),
        ("rotselleri".to_string(), Category::Vegetables),
        ("palsternacka".to_string(), Category::Vegetables),
        ("rova".to_string(), Category::Vegetables),
        ("kålrot".to_string(), Category::Vegetables),
        ("rädisa".to_string(), Category::Vegetables),
        ("rädisor".to_string(), Category::Vegetables),
        ("rödbeta".to_string(), Category::Vegetables),
        ("rödbetor".to_string(), Category::Vegetables),
        ("majs".to_string(), Category::Vegetables),
        ("majskolv".to_string(), Category::Vegetables),
        ("kronärtskocka".to_string(), Category::Vegetables),
        ("sparris".to_string(), Category::Vegetables),
        ("grönsparris".to_string(), Category::Vegetables),
        ("vitsparris".to_string(), Category::Vegetables),
        ("fänkål".to_string(), Category::Vegetables),
        ("jordärtskocka".to_string(), Category::Vegetables),
        ("haricots verts".to_string(), Category::Vegetables),
        ("haricotsverts".to_string(), Category::Vegetables),
        ("bönor".to_string(), Category::Vegetables),
        ("sockerärtor".to_string(), Category::Vegetables),
        ("ärtor".to_string(), Category::Vegetables),
        ("avokado".to_string(), Category::Vegetables),
        ("svamp".to_string(), Category::Vegetables),
        ("svampar".to_string(), Category::Vegetables),
        ("champinjoner".to_string(), Category::Vegetables),
        ("portobellosvamp".to_string(), Category::Vegetables),
        ("shiitakesvamp".to_string(), Category::Vegetables),
        ("kantareller".to_string(), Category::Vegetables),
        ("karljohansvamp".to_string(), Category::Vegetables),
        ("ostronskivling".to_string(), Category::Vegetables),
        ("enoki".to_string(), Category::Vegetables),
        ("jalapeño".to_string(), Category::Vegetables),
        ("jalapeno".to_string(), Category::Vegetables),
        ("chili".to_string(), Category::Vegetables),
        ("röd chili".to_string(), Category::Vegetables),
        ("rödchili".to_string(), Category::Vegetables),
        ("grön chili".to_string(), Category::Vegetables),
        ("grönchili".to_string(), Category::Vegetables),
        ("ingefära".to_string(), Category::Vegetables),
        ("färsk ingefära".to_string(), Category::Vegetables),
        ("pak choi".to_string(), Category::Vegetables),
        ("pakchoi".to_string(), Category::Vegetables),
        ("kinakål".to_string(), Category::Vegetables),
        ("vattenkrasse".to_string(), Category::Vegetables),
        ("rättika".to_string(), Category::Vegetables),
        ("kålrabbi".to_string(), Category::Vegetables),
        ("mangold".to_string(), Category::Vegetables),
        ("collardkål".to_string(), Category::Vegetables),
        ("sugarsnap".to_string(), Category::Vegetables),
        // Frukt
        ("äpple".to_string(), Category::Fruit),
        ("äpplen".to_string(), Category::Fruit),
        ("päron".to_string(), Category::Fruit),
        ("banan".to_string(), Category::Fruit),
        ("bananer".to_string(), Category::Fruit),
        ("apelsin".to_string(), Category::Fruit),
        ("apelsiner".to_string(), Category::Fruit),
        ("citron".to_string(), Category::Fruit),
        ("citroner".to_string(), Category::Fruit),
        ("lime".to_string(), Category::Fruit),
        ("grapefrukt".to_string(), Category::Fruit),
        ("mandarin".to_string(), Category::Fruit),
        ("mandariner".to_string(), Category::Fruit),
        ("clementin".to_string(), Category::Fruit),
        ("clementiner".to_string(), Category::Fruit),
        ("jordgubbe".to_string(), Category::Fruit),
        ("jordgubbar".to_string(), Category::Fruit),
        ("hallon".to_string(), Category::Fruit),
        ("blåbär".to_string(), Category::Fruit),
        ("björnbär".to_string(), Category::Fruit),
        ("tranbär".to_string(), Category::Fruit),
        ("lingon".to_string(), Category::Fruit),
        ("krusbär".to_string(), Category::Fruit),
        ("vinbär".to_string(), Category::Fruit),
        ("röda vinbär".to_string(), Category::Fruit),
        ("svarta vinbär".to_string(), Category::Fruit),
        ("vindruvor".to_string(), Category::Fruit),
        ("gröna vindruvor".to_string(), Category::Fruit),
        ("röda vindruvor".to_string(), Category::Fruit),
        ("vattenmelon".to_string(), Category::Fruit),
        ("melon".to_string(), Category::Fruit),
        ("honungsmelon".to_string(), Category::Fruit),
        ("cantaloupe".to_string(), Category::Fruit),
        ("mango".to_string(), Category::Fruit),
        ("ananas".to_string(), Category::Fruit),
        ("papaya".to_string(), Category::Fruit),
        ("kiwi".to_string(), Category::Fruit),
        ("persika".to_string(), Category::Fruit),
        ("nektarin".to_string(), Category::Fruit),
        ("plommon".to_string(), Category::Fruit),
        ("körsbär".to_string(), Category::Fruit),
        ("fikon".to_string(), Category::Fruit),
        ("dadlar".to_string(), Category::Fruit),
        ("russin".to_string(), Category::Fruit),
        ("torkade aprikoser".to_string(), Category::Fruit),
        ("aprikos".to_string(), Category::Fruit),
        ("kokos".to_string(), Category::Fruit),
        ("kokosnöt".to_string(), Category::Fruit),
        ("passionsfrukt".to_string(), Category::Fruit),
        ("granatäpple".to_string(), Category::Fruit),
        ("lychee".to_string(), Category::Fruit),
        ("hjortron".to_string(), Category::Fruit),
        ("åkerbär".to_string(), Category::Fruit),
        // Mejeri
        ("mjölk".to_string(), Category::Dairy),
        ("helmjölk".to_string(), Category::Dairy),
        ("standardmjölk".to_string(), Category::Dairy),
        ("lättmjölk".to_string(), Category::Dairy),
        ("mellanmjölk".to_string(), Category::Dairy),
        ("havremjölk".to_string(), Category::Dairy),
        ("mandelmjölk".to_string(), Category::Dairy),
        ("sojamjölk".to_string(), Category::Dairy),
        ("oatly".to_string(), Category::Dairy),
        ("smör".to_string(), Category::Dairy),
        ("osaltat smör".to_string(), Category::Dairy),
        ("saltat smör".to_string(), Category::Dairy),
        ("margarin".to_string(), Category::Dairy),
        ("vispgrädde".to_string(), Category::Dairy),
        ("matlagningsgrädde".to_string(), Category::Dairy),
        ("lätt grädde".to_string(), Category::Dairy),
        ("grädde".to_string(), Category::Dairy),
        ("gräddfil".to_string(), Category::Dairy),
        ("filmjölk".to_string(), Category::Dairy),
        ("fil".to_string(), Category::Dairy),
        ("yoghurt".to_string(), Category::Dairy),
        ("naturell yoghurt".to_string(), Category::Dairy),
        ("grekisk yoghurt".to_string(), Category::Dairy),
        ("kvarg".to_string(), Category::Dairy),
        ("kesella".to_string(), Category::Dairy),
        ("keso".to_string(), Category::Dairy),
        ("crème fraîche".to_string(), Category::Dairy),
        ("creme fraiche".to_string(), Category::Dairy),
        ("cremefraiche".to_string(), Category::Dairy),
        ("ricotta".to_string(), Category::Dairy),
        ("mascarpone".to_string(), Category::Dairy),
        ("färskost".to_string(), Category::Dairy),
        ("philadelphiaost".to_string(), Category::Dairy),
        ("ost".to_string(), Category::Dairy),
        ("cheddar".to_string(), Category::Dairy),
        ("gouda".to_string(), Category::Dairy),
        ("schweizerost".to_string(), Category::Dairy),
        ("parmesan".to_string(), Category::Dairy),
        ("parmesanost".to_string(), Category::Dairy),
        ("mozzarella".to_string(), Category::Dairy),
        ("fetaost".to_string(), Category::Dairy),
        ("feta".to_string(), Category::Dairy),
        ("brie".to_string(), Category::Dairy),
        ("camembert".to_string(), Category::Dairy),
        ("mögelost".to_string(), Category::Dairy),
        ("gorgonzola".to_string(), Category::Dairy),
        ("roquefort".to_string(), Category::Dairy),
        ("halloumi".to_string(), Category::Dairy),
        ("havarti".to_string(), Category::Dairy),
        ("prästost".to_string(), Category::Dairy),
        ("sveciaost".to_string(), Category::Dairy),
        ("lagrad ost".to_string(), Category::Dairy),
        ("riven ost".to_string(), Category::Dairy),
        ("smältost".to_string(), Category::Dairy),
        ("ägg".to_string(), Category::Dairy),
        ("äggula".to_string(), Category::Dairy),
        ("äggvita".to_string(), Category::Dairy),
        ("vispad grädde".to_string(), Category::Dairy),
        ("messmör".to_string(), Category::Dairy),
        // Protein
        ("kyckling".to_string(), Category::Protein),
        ("kycklingbröst".to_string(), Category::Protein),
        ("kycklingfilé".to_string(), Category::Protein),
        ("kycklingfile".to_string(), Category::Protein),
        ("kycklinglår".to_string(), Category::Protein),
        ("kycklingklubbor".to_string(), Category::Protein),
        ("kycklingvingar".to_string(), Category::Protein),
        ("hel kyckling".to_string(), Category::Protein),
        ("helkyckling".to_string(), Category::Protein),
        ("kycklingfärs".to_string(), Category::Protein),
        ("nötfärs".to_string(), Category::Protein),
        ("nötkött".to_string(), Category::Protein),
        ("biff".to_string(), Category::Protein),
        ("entrecôte".to_string(), Category::Protein),
        ("entrecote".to_string(), Category::Protein),
        ("ryggbiff".to_string(), Category::Protein),
        ("oxfilé".to_string(), Category::Protein),
        ("oxfile".to_string(), Category::Protein),
        ("rostbiff".to_string(), Category::Protein),
        ("bringa".to_string(), Category::Protein),
        ("högrev".to_string(), Category::Protein),
        ("grytbitar".to_string(), Category::Protein),
        ("revbensspjäll".to_string(), Category::Protein),
        ("nötrevben".to_string(), Category::Protein),
        ("fläskfärs".to_string(), Category::Protein),
        ("fläskkött".to_string(), Category::Protein),
        ("fläskkotlett".to_string(), Category::Protein),
        ("fläskfilé".to_string(), Category::Protein),
        ("fläskfile".to_string(), Category::Protein),
        ("fläskbog".to_string(), Category::Protein),
        ("sidfläsk".to_string(), Category::Protein),
        ("rimmat sidfläsk".to_string(), Category::Protein),
        ("bacon".to_string(), Category::Protein),
        ("skinka".to_string(), Category::Protein),
        ("kokt skinka".to_string(), Category::Protein),
        ("rökt skinka".to_string(), Category::Protein),
        ("prosciutto".to_string(), Category::Protein),
        ("pancetta".to_string(), Category::Protein),
        ("korv".to_string(), Category::Protein),
        ("falukorv".to_string(), Category::Protein),
        ("prinskorv".to_string(), Category::Protein),
        ("varmkorv".to_string(), Category::Protein),
        ("chorizo".to_string(), Category::Protein),
        ("salami".to_string(), Category::Protein),
        ("pepperoni".to_string(), Category::Protein),
        ("leverpastej".to_string(), Category::Protein),
        ("leverpostej".to_string(), Category::Protein),
        ("köttbullar".to_string(), Category::Protein),
        ("kalkon".to_string(), Category::Protein),
        ("kalkonbröst".to_string(), Category::Protein),
        ("kalkonsfärs".to_string(), Category::Protein),
        ("lammfärs".to_string(), Category::Protein),
        ("lammkött".to_string(), Category::Protein),
        ("lammkotlett".to_string(), Category::Protein),
        ("lammracks".to_string(), Category::Protein),
        ("lammbog".to_string(), Category::Protein),
        ("lammlägg".to_string(), Category::Protein),
        ("renskav".to_string(), Category::Protein),
        ("renkött".to_string(), Category::Protein),
        ("renfärs".to_string(), Category::Protein),
        ("älgkött".to_string(), Category::Protein),
        ("älgfärs".to_string(), Category::Protein),
        ("vildsvin".to_string(), Category::Protein),
        ("vildsvinsfärs".to_string(), Category::Protein),
        ("lax".to_string(), Category::Protein),
        ("laxfilé".to_string(), Category::Protein),
        ("laxfile".to_string(), Category::Protein),
        ("rökt lax".to_string(), Category::Protein),
        ("gravlax".to_string(), Category::Protein),
        ("tonfisk".to_string(), Category::Protein),
        ("tonfisk på burk".to_string(), Category::Protein),
        ("torsk".to_string(), Category::Protein),
        ("hälleflundra".to_string(), Category::Protein),
        ("röding".to_string(), Category::Protein),
        ("öring".to_string(), Category::Protein),
        ("abborre".to_string(), Category::Protein),
        ("gädda".to_string(), Category::Protein),
        ("sill".to_string(), Category::Protein),
        ("strömming".to_string(), Category::Protein),
        ("inlagd sill".to_string(), Category::Protein),
        ("räkor".to_string(), Category::Protein),
        ("tigerräkor".to_string(), Category::Protein),
        ("pilgrimsmusslor".to_string(), Category::Protein),
        ("krabba".to_string(), Category::Protein),
        ("hummer".to_string(), Category::Protein),
        ("musslor".to_string(), Category::Protein),
        ("blåmusslor".to_string(), Category::Protein),
        ("tofu".to_string(), Category::Protein),
        ("fast tofu".to_string(), Category::Protein),
        ("silkestofu".to_string(), Category::Protein),
        ("tempeh".to_string(), Category::Protein),
        ("svarta bönor".to_string(), Category::Protein),
        ("kidneybönor".to_string(), Category::Protein),
        ("kikärtor".to_string(), Category::Protein),
        ("linser".to_string(), Category::Protein),
        ("vita bönor".to_string(), Category::Protein),
        ("pintobönor".to_string(), Category::Protein),
        ("edamame".to_string(), Category::Protein),
        ("blodpudding".to_string(), Category::Protein),
        ("pölsa".to_string(), Category::Protein),
        // Skafferi
        ("ris".to_string(), Category::Pantry),
        ("vitt ris".to_string(), Category::Pantry),
        ("brunt ris".to_string(), Category::Pantry),
        ("jasminris".to_string(), Category::Pantry),
        ("basmatris".to_string(), Category::Pantry),
        ("pasta".to_string(), Category::Pantry),
        ("spaghetti".to_string(), Category::Pantry),
        ("penne".to_string(), Category::Pantry),
        ("fettuccine".to_string(), Category::Pantry),
        ("rigatoni".to_string(), Category::Pantry),
        ("lasagneplattor".to_string(), Category::Pantry),
        ("äggnudlar".to_string(), Category::Pantry),
        ("ramennudlar".to_string(), Category::Pantry),
        ("bröd".to_string(), Category::Pantry),
        ("vitt bröd".to_string(), Category::Pantry),
        ("fullkornsbröd".to_string(), Category::Pantry),
        ("surdegsbröd".to_string(), Category::Pantry),
        ("baguette".to_string(), Category::Pantry),
        ("knäckebröd".to_string(), Category::Pantry),
        ("wasa".to_string(), Category::Pantry),
        ("kavring".to_string(), Category::Pantry),
        ("tortillas".to_string(), Category::Pantry),
        ("pitabröd".to_string(), Category::Pantry),
        ("vetemjöl".to_string(), Category::Pantry),
        ("mjöl".to_string(), Category::Pantry),
        ("brödmjöl".to_string(), Category::Pantry),
        ("fullkornsmjöl".to_string(), Category::Pantry),
        ("majsmjöl".to_string(), Category::Pantry),
        ("havregryn".to_string(), Category::Pantry),
        ("müsli".to_string(), Category::Pantry),
        ("flingor".to_string(), Category::Pantry),
        ("ströbröd".to_string(), Category::Pantry),
        ("pankoströbröd".to_string(), Category::Pantry),
        ("kycklingbuljong".to_string(), Category::Pantry),
        ("köttbuljong".to_string(), Category::Pantry),
        ("grönsaksbuljong".to_string(), Category::Pantry),
        ("kycklingfond".to_string(), Category::Pantry),
        ("köttfond".to_string(), Category::Pantry),
        ("grönsaksfond".to_string(), Category::Pantry),
        ("buljong".to_string(), Category::Pantry),
        ("olivolja".to_string(), Category::Pantry),
        ("rapsolja".to_string(), Category::Pantry),
        ("matolja".to_string(), Category::Pantry),
        ("kokosolja".to_string(), Category::Pantry),
        ("sesamolja".to_string(), Category::Pantry),
        ("krossade tomater".to_string(), Category::Pantry),
        ("hackade tomater".to_string(), Category::Pantry),
        ("tomater på burk".to_string(), Category::Pantry),
        ("tomatpuré".to_string(), Category::Pantry),
        ("tomatsås".to_string(), Category::Pantry),
        ("sojasås".to_string(), Category::Pantry),
        ("worcestershiresås".to_string(), Category::Pantry),
        ("chilisås".to_string(), Category::Pantry),
        ("ketchup".to_string(), Category::Pantry),
        ("senap".to_string(), Category::Pantry),
        ("dijonsenap".to_string(), Category::Pantry),
        ("majonnäs".to_string(), Category::Pantry),
        ("ättika".to_string(), Category::Pantry),
        ("vinäger".to_string(), Category::Pantry),
        ("vit vinäger".to_string(), Category::Pantry),
        ("äppelcidervinäger".to_string(), Category::Pantry),
        ("balsamvinäger".to_string(), Category::Pantry),
        ("rödvinsvinäger".to_string(), Category::Pantry),
        ("socker".to_string(), Category::Pantry),
        ("brunt socker".to_string(), Category::Pantry),
        ("farinsocker".to_string(), Category::Pantry),
        ("florsocker".to_string(), Category::Pantry),
        ("honung".to_string(), Category::Pantry),
        ("lönnsirap".to_string(), Category::Pantry),
        ("sirap".to_string(), Category::Pantry),
        ("bakpulver".to_string(), Category::Pantry),
        ("bikarbonat".to_string(), Category::Pantry),
        ("jäst".to_string(), Category::Pantry),
        ("vaniljextrakt".to_string(), Category::Pantry),
        ("vaniljsocker".to_string(), Category::Pantry),
        ("kakao".to_string(), Category::Pantry),
        ("choklad".to_string(), Category::Pantry),
        ("chokladbitar".to_string(), Category::Pantry),
        ("mörk choklad".to_string(), Category::Pantry),
        ("jordnötssmör".to_string(), Category::Pantry),
        ("mandelsmör".to_string(), Category::Pantry),
        ("sylt".to_string(), Category::Pantry),
        ("lingonsylt".to_string(), Category::Pantry),
        ("hjortronsylt".to_string(), Category::Pantry),
        ("marmelad".to_string(), Category::Pantry),
        ("salsa".to_string(), Category::Pantry),
        ("kokosmjölk".to_string(), Category::Pantry),
        ("fisksås".to_string(), Category::Pantry),
        ("ostronsås".to_string(), Category::Pantry),
        ("hoisinsås".to_string(), Category::Pantry),
        ("sriracha".to_string(), Category::Pantry),
        ("tahini".to_string(), Category::Pantry),
        ("vin".to_string(), Category::Pantry),
        ("vitt vin".to_string(), Category::Pantry),
        ("rödvin".to_string(), Category::Pantry),
        ("öl".to_string(), Category::Pantry),
        ("mandlar".to_string(), Category::Pantry),
        ("valnötter".to_string(), Category::Pantry),
        ("pekannötter".to_string(), Category::Pantry),
        ("cashewnötter".to_string(), Category::Pantry),
        ("jordnötter".to_string(), Category::Pantry),
        ("pinjenötter".to_string(), Category::Pantry),
        ("solrosfrön".to_string(), Category::Pantry),
        ("sesamfrön".to_string(), Category::Pantry),
        ("pumpafrön".to_string(), Category::Pantry),
        ("maizena".to_string(), Category::Pantry),
        ("majsstärkelse".to_string(), Category::Pantry),
        ("potatismjöl".to_string(), Category::Pantry),
        ("kaviar".to_string(), Category::Pantry),
        ("rödbetor på burk".to_string(), Category::Pantry),
        ("gurka på burk".to_string(), Category::Pantry),
        ("inlagd gurka".to_string(), Category::Pantry),
        ("oliver".to_string(), Category::Pantry),
        ("kapris".to_string(), Category::Pantry),
        // Kryddor
        ("salt".to_string(), Category::Spices),
        ("havssalt".to_string(), Category::Spices),
        ("grovt salt".to_string(), Category::Spices),
        ("svartpeppar".to_string(), Category::Spices),
        ("vitpeppar".to_string(), Category::Spices),
        ("chiliflingor".to_string(), Category::Spices),
        ("cayennepeppar".to_string(), Category::Spices),
        ("paprikapulver".to_string(), Category::Spices),
        ("rökt paprika".to_string(), Category::Spices),
        ("vitlökspulver".to_string(), Category::Spices),
        ("lökpulver".to_string(), Category::Spices),
        ("spiskummin".to_string(), Category::Spices),
        ("kummin".to_string(), Category::Spices),
        ("koriander".to_string(), Category::Spices),
        ("gurkmeja".to_string(), Category::Spices),
        ("kanel".to_string(), Category::Spices),
        ("muskot".to_string(), Category::Spices),
        ("muskotnöt".to_string(), Category::Spices),
        ("kryddpeppar".to_string(), Category::Spices),
        ("kryddnejlika".to_string(), Category::Spices),
        ("nejlikor".to_string(), Category::Spices),
        ("kardemumma".to_string(), Category::Spices),
        ("ingefärapulver".to_string(), Category::Spices),
        ("torkad ingefära".to_string(), Category::Spices),
        ("oregano".to_string(), Category::Spices),
        ("torkad oregano".to_string(), Category::Spices),
        ("basilika".to_string(), Category::Spices),
        ("torkad basilika".to_string(), Category::Spices),
        ("timjan".to_string(), Category::Spices),
        ("torkad timjan".to_string(), Category::Spices),
        ("rosmarin".to_string(), Category::Spices),
        ("torkad rosmarin".to_string(), Category::Spices),
        ("lagerblad".to_string(), Category::Spices),
        ("persilja".to_string(), Category::Spices),
        ("torkad persilja".to_string(), Category::Spices),
        ("färsk persilja".to_string(), Category::Spices),
        ("färsk koriander".to_string(), Category::Spices),
        ("dill".to_string(), Category::Spices),
        ("färsk dill".to_string(), Category::Spices),
        ("gräslök".to_string(), Category::Spices),
        ("salvia".to_string(), Category::Spices),
        ("torkad salvia".to_string(), Category::Spices),
        ("dragon".to_string(), Category::Spices),
        ("mejram".to_string(), Category::Spices),
        ("chilipulver".to_string(), Category::Spices),
        ("tacokrydda".to_string(), Category::Spices),
        ("italiensk kryddblandning".to_string(), Category::Spices),
        ("senapsfrön".to_string(), Category::Spices),
        ("fänkålsfrön".to_string(), Category::Spices),
        ("kumminfrön".to_string(), Category::Spices),
        ("stjärnanis".to_string(), Category::Spices),
        ("saffran".to_string(), Category::Spices),
        ("vaniljstång".to_string(), Category::Spices),
        ("mynta".to_string(), Category::Spices),
        ("färsk mynta".to_string(), Category::Spices),
        ("citrongräs".to_string(), Category::Spices),
        ("pepparrot".to_string(), Category::Spices),
        ("allkrydda".to_string(), Category::Spices),
    ])
}
