use std::collections::HashMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize, Eq, PartialOrd, Ord, Copy)]
pub enum Category {
    Vegetables,
    Fruit,
    Dairy,
    Protein,
    Pantry,
    Spices,
    Misc,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Dish {
    pub name: String,
    pub ingredients: Vec<Ingredient>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, PartialOrd)]
pub struct Ingredient {
    pub name: String,
    pub category: Category,
    pub frozen: bool,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Database {
    pub dishes: Vec<Dish>,
}

pub fn ingredient_category_db() -> HashMap<String, Category> {
    HashMap::from([
        // Vegetables
        ("onion".to_string(), Category::Vegetables),
        ("yellow onion".to_string(), Category::Vegetables),
        ("red onion".to_string(), Category::Vegetables),
        ("white onion".to_string(), Category::Vegetables),
        ("green onion".to_string(), Category::Vegetables),
        ("scallion".to_string(), Category::Vegetables),
        ("shallot".to_string(), Category::Vegetables),
        ("shallots".to_string(), Category::Vegetables),
        ("leek".to_string(), Category::Vegetables),
        ("leeks".to_string(), Category::Vegetables),
        ("garlic".to_string(), Category::Vegetables),
        ("garlic clove".to_string(), Category::Vegetables),
        ("garlic cloves".to_string(), Category::Vegetables),
        ("carrot".to_string(), Category::Vegetables),
        ("carrots".to_string(), Category::Vegetables),
        ("potato".to_string(), Category::Vegetables),
        ("potatoes".to_string(), Category::Vegetables),
        ("sweet potato".to_string(), Category::Vegetables),
        ("sweet potatoes".to_string(), Category::Vegetables),
        ("tomato".to_string(), Category::Vegetables),
        ("tomatoes".to_string(), Category::Vegetables),
        ("cherry tomatoes".to_string(), Category::Vegetables),
        ("roma tomatoes".to_string(), Category::Vegetables),
        ("bell pepper".to_string(), Category::Vegetables),
        ("bell peppers".to_string(), Category::Vegetables),
        ("red bell pepper".to_string(), Category::Vegetables),
        ("green bell pepper".to_string(), Category::Vegetables),
        ("yellow bell pepper".to_string(), Category::Vegetables),
        ("cucumber".to_string(), Category::Vegetables),
        ("zucchini".to_string(), Category::Vegetables),
        ("eggplant".to_string(), Category::Vegetables),
        ("broccoli".to_string(), Category::Vegetables),
        ("cauliflower".to_string(), Category::Vegetables),
        ("cabbage".to_string(), Category::Vegetables),
        ("red cabbage".to_string(), Category::Vegetables),
        ("green cabbage".to_string(), Category::Vegetables),
        ("kale".to_string(), Category::Vegetables),
        ("brussels sprouts".to_string(), Category::Vegetables),
        ("spinach".to_string(), Category::Vegetables),
        ("arugula".to_string(), Category::Vegetables),
        ("iceberg lettuce".to_string(), Category::Vegetables),
        ("romaine lettuce".to_string(), Category::Vegetables),
        ("lettuce".to_string(), Category::Vegetables),
        ("celery".to_string(), Category::Vegetables),
        ("celery root".to_string(), Category::Vegetables),
        ("parsnip".to_string(), Category::Vegetables),
        ("turnip".to_string(), Category::Vegetables),
        ("radish".to_string(), Category::Vegetables),
        ("beet".to_string(), Category::Vegetables),
        ("beets".to_string(), Category::Vegetables),
        ("corn".to_string(), Category::Vegetables),
        ("corn on the cob".to_string(), Category::Vegetables),
        ("artichoke".to_string(), Category::Vegetables),
        ("asparagus".to_string(), Category::Vegetables),
        ("fennel".to_string(), Category::Vegetables),
        ("green beans".to_string(), Category::Vegetables),
        ("snap peas".to_string(), Category::Vegetables),
        ("snow peas".to_string(), Category::Vegetables),
        ("peas".to_string(), Category::Vegetables),
        ("avocado".to_string(), Category::Vegetables),
        ("mushroom".to_string(), Category::Vegetables),
        ("mushrooms".to_string(), Category::Vegetables),
        ("button mushrooms".to_string(), Category::Vegetables),
        ("portobello mushrooms".to_string(), Category::Vegetables),
        ("shiitake mushrooms".to_string(), Category::Vegetables),
        ("cremini mushrooms".to_string(), Category::Vegetables),
        ("jalapeno".to_string(), Category::Vegetables),
        ("jalapeño".to_string(), Category::Vegetables),
        ("chili pepper".to_string(), Category::Vegetables),
        ("chili peppers".to_string(), Category::Vegetables),
        ("ginger".to_string(), Category::Vegetables),
        ("fresh ginger".to_string(), Category::Vegetables),
        ("bok choy".to_string(), Category::Vegetables),
        ("napa cabbage".to_string(), Category::Vegetables),
        ("watercress".to_string(), Category::Vegetables),
        ("rutabaga".to_string(), Category::Vegetables),
        ("kohlrabi".to_string(), Category::Vegetables),
        ("collard greens".to_string(), Category::Vegetables),
        ("swiss chard".to_string(), Category::Vegetables),
        // Fruit
        ("apple".to_string(), Category::Fruit),
        ("apples".to_string(), Category::Fruit),
        ("pear".to_string(), Category::Fruit),
        ("pears".to_string(), Category::Fruit),
        ("banana".to_string(), Category::Fruit),
        ("bananas".to_string(), Category::Fruit),
        ("orange".to_string(), Category::Fruit),
        ("oranges".to_string(), Category::Fruit),
        ("lemon".to_string(), Category::Fruit),
        ("lemons".to_string(), Category::Fruit),
        ("lime".to_string(), Category::Fruit),
        ("limes".to_string(), Category::Fruit),
        ("grapefruit".to_string(), Category::Fruit),
        ("mandarin".to_string(), Category::Fruit),
        ("clementine".to_string(), Category::Fruit),
        ("strawberry".to_string(), Category::Fruit),
        ("strawberries".to_string(), Category::Fruit),
        ("raspberry".to_string(), Category::Fruit),
        ("raspberries".to_string(), Category::Fruit),
        ("blueberry".to_string(), Category::Fruit),
        ("blueberries".to_string(), Category::Fruit),
        ("blackberry".to_string(), Category::Fruit),
        ("blackberries".to_string(), Category::Fruit),
        ("cranberry".to_string(), Category::Fruit),
        ("cranberries".to_string(), Category::Fruit),
        ("grapes".to_string(), Category::Fruit),
        ("red grapes".to_string(), Category::Fruit),
        ("green grapes".to_string(), Category::Fruit),
        ("watermelon".to_string(), Category::Fruit),
        ("cantaloupe".to_string(), Category::Fruit),
        ("honeydew".to_string(), Category::Fruit),
        ("mango".to_string(), Category::Fruit),
        ("pineapple".to_string(), Category::Fruit),
        ("papaya".to_string(), Category::Fruit),
        ("kiwi".to_string(), Category::Fruit),
        ("peach".to_string(), Category::Fruit),
        ("peaches".to_string(), Category::Fruit),
        ("nectarine".to_string(), Category::Fruit),
        ("plum".to_string(), Category::Fruit),
        ("plums".to_string(), Category::Fruit),
        ("cherries".to_string(), Category::Fruit),
        ("fig".to_string(), Category::Fruit),
        ("figs".to_string(), Category::Fruit),
        ("dates".to_string(), Category::Fruit),
        ("raisins".to_string(), Category::Fruit),
        ("dried apricots".to_string(), Category::Fruit),
        ("apricot".to_string(), Category::Fruit),
        ("coconut".to_string(), Category::Fruit),
        ("passion fruit".to_string(), Category::Fruit),
        ("pomegranate".to_string(), Category::Fruit),
        ("lychee".to_string(), Category::Fruit),
        // Dairy
        ("milk".to_string(), Category::Dairy),
        ("whole milk".to_string(), Category::Dairy),
        ("skim milk".to_string(), Category::Dairy),
        ("2% milk".to_string(), Category::Dairy),
        ("oat milk".to_string(), Category::Dairy),
        ("almond milk".to_string(), Category::Dairy),
        ("soy milk".to_string(), Category::Dairy),
        ("butter".to_string(), Category::Dairy),
        ("unsalted butter".to_string(), Category::Dairy),
        ("salted butter".to_string(), Category::Dairy),
        ("margarine".to_string(), Category::Dairy),
        ("heavy cream".to_string(), Category::Dairy),
        ("heavy whipping cream".to_string(), Category::Dairy),
        ("half and half".to_string(), Category::Dairy),
        ("sour cream".to_string(), Category::Dairy),
        ("cream cheese".to_string(), Category::Dairy),
        ("yogurt".to_string(), Category::Dairy),
        ("greek yogurt".to_string(), Category::Dairy),
        ("plain yogurt".to_string(), Category::Dairy),
        ("cottage cheese".to_string(), Category::Dairy),
        ("ricotta".to_string(), Category::Dairy),
        ("mascarpone".to_string(), Category::Dairy),
        ("cheese".to_string(), Category::Dairy),
        ("cheddar".to_string(), Category::Dairy),
        ("cheddar cheese".to_string(), Category::Dairy),
        ("gouda".to_string(), Category::Dairy),
        ("swiss cheese".to_string(), Category::Dairy),
        ("parmesan".to_string(), Category::Dairy),
        ("parmesan cheese".to_string(), Category::Dairy),
        ("mozzarella".to_string(), Category::Dairy),
        ("feta".to_string(), Category::Dairy),
        ("feta cheese".to_string(), Category::Dairy),
        ("brie".to_string(), Category::Dairy),
        ("camembert".to_string(), Category::Dairy),
        ("blue cheese".to_string(), Category::Dairy),
        ("gorgonzola".to_string(), Category::Dairy),
        ("halloumi".to_string(), Category::Dairy),
        ("monterey jack".to_string(), Category::Dairy),
        ("pepper jack".to_string(), Category::Dairy),
        ("american cheese".to_string(), Category::Dairy),
        ("provolone".to_string(), Category::Dairy),
        ("gruyere".to_string(), Category::Dairy),
        ("eggs".to_string(), Category::Dairy),
        ("egg".to_string(), Category::Dairy),
        ("egg yolk".to_string(), Category::Dairy),
        ("egg white".to_string(), Category::Dairy),
        ("whipped cream".to_string(), Category::Dairy),
        // Protein
        ("chicken breast".to_string(), Category::Protein),
        ("chicken breasts".to_string(), Category::Protein),
        ("chicken thighs".to_string(), Category::Protein),
        ("chicken legs".to_string(), Category::Protein),
        ("chicken wings".to_string(), Category::Protein),
        ("whole chicken".to_string(), Category::Protein),
        ("ground chicken".to_string(), Category::Protein),
        ("chicken".to_string(), Category::Protein),
        ("ground beef".to_string(), Category::Protein),
        ("beef".to_string(), Category::Protein),
        ("steak".to_string(), Category::Protein),
        ("ribeye".to_string(), Category::Protein),
        ("sirloin".to_string(), Category::Protein),
        ("tenderloin".to_string(), Category::Protein),
        ("brisket".to_string(), Category::Protein),
        ("chuck roast".to_string(), Category::Protein),
        ("short ribs".to_string(), Category::Protein),
        ("beef ribs".to_string(), Category::Protein),
        ("ground pork".to_string(), Category::Protein),
        ("pork".to_string(), Category::Protein),
        ("pork chops".to_string(), Category::Protein),
        ("pork tenderloin".to_string(), Category::Protein),
        ("pork shoulder".to_string(), Category::Protein),
        ("pork belly".to_string(), Category::Protein),
        ("baby back ribs".to_string(), Category::Protein),
        ("spare ribs".to_string(), Category::Protein),
        ("bacon".to_string(), Category::Protein),
        ("ham".to_string(), Category::Protein),
        ("prosciutto".to_string(), Category::Protein),
        ("pancetta".to_string(), Category::Protein),
        ("sausage".to_string(), Category::Protein),
        ("italian sausage".to_string(), Category::Protein),
        ("breakfast sausage".to_string(), Category::Protein),
        ("chorizo".to_string(), Category::Protein),
        ("ground turkey".to_string(), Category::Protein),
        ("turkey".to_string(), Category::Protein),
        ("turkey breast".to_string(), Category::Protein),
        ("ground lamb".to_string(), Category::Protein),
        ("lamb".to_string(), Category::Protein),
        ("lamb chops".to_string(), Category::Protein),
        ("rack of lamb".to_string(), Category::Protein),
        ("leg of lamb".to_string(), Category::Protein),
        ("salmon".to_string(), Category::Protein),
        ("salmon fillet".to_string(), Category::Protein),
        ("smoked salmon".to_string(), Category::Protein),
        ("tuna".to_string(), Category::Protein),
        ("canned tuna".to_string(), Category::Protein),
        ("tilapia".to_string(), Category::Protein),
        ("cod".to_string(), Category::Protein),
        ("halibut".to_string(), Category::Protein),
        ("shrimp".to_string(), Category::Protein),
        ("prawns".to_string(), Category::Protein),
        ("scallops".to_string(), Category::Protein),
        ("crab".to_string(), Category::Protein),
        ("lobster".to_string(), Category::Protein),
        ("clams".to_string(), Category::Protein),
        ("mussels".to_string(), Category::Protein),
        ("tofu".to_string(), Category::Protein),
        ("firm tofu".to_string(), Category::Protein),
        ("silken tofu".to_string(), Category::Protein),
        ("tempeh".to_string(), Category::Protein),
        ("black beans".to_string(), Category::Protein),
        ("kidney beans".to_string(), Category::Protein),
        ("chickpeas".to_string(), Category::Protein),
        ("lentils".to_string(), Category::Protein),
        ("white beans".to_string(), Category::Protein),
        ("pinto beans".to_string(), Category::Protein),
        ("edamame".to_string(), Category::Protein),
        ("hot dogs".to_string(), Category::Protein),
        ("pepperoni".to_string(), Category::Protein),
        ("salami".to_string(), Category::Protein),
        // Pantry
        ("rice".to_string(), Category::Pantry),
        ("white rice".to_string(), Category::Pantry),
        ("brown rice".to_string(), Category::Pantry),
        ("jasmine rice".to_string(), Category::Pantry),
        ("basmati rice".to_string(), Category::Pantry),
        ("pasta".to_string(), Category::Pantry),
        ("spaghetti".to_string(), Category::Pantry),
        ("penne".to_string(), Category::Pantry),
        ("fettuccine".to_string(), Category::Pantry),
        ("rigatoni".to_string(), Category::Pantry),
        ("lasagna noodles".to_string(), Category::Pantry),
        ("egg noodles".to_string(), Category::Pantry),
        ("ramen noodles".to_string(), Category::Pantry),
        ("bread".to_string(), Category::Pantry),
        ("white bread".to_string(), Category::Pantry),
        ("whole wheat bread".to_string(), Category::Pantry),
        ("sourdough".to_string(), Category::Pantry),
        ("baguette".to_string(), Category::Pantry),
        ("tortillas".to_string(), Category::Pantry),
        ("flour tortillas".to_string(), Category::Pantry),
        ("corn tortillas".to_string(), Category::Pantry),
        ("pita bread".to_string(), Category::Pantry),
        ("all-purpose flour".to_string(), Category::Pantry),
        ("flour".to_string(), Category::Pantry),
        ("bread flour".to_string(), Category::Pantry),
        ("whole wheat flour".to_string(), Category::Pantry),
        ("cornmeal".to_string(), Category::Pantry),
        ("oats".to_string(), Category::Pantry),
        ("rolled oats".to_string(), Category::Pantry),
        ("breadcrumbs".to_string(), Category::Pantry),
        ("panko breadcrumbs".to_string(), Category::Pantry),
        ("chicken broth".to_string(), Category::Pantry),
        ("beef broth".to_string(), Category::Pantry),
        ("vegetable broth".to_string(), Category::Pantry),
        ("chicken stock".to_string(), Category::Pantry),
        ("beef stock".to_string(), Category::Pantry),
        ("olive oil".to_string(), Category::Pantry),
        ("vegetable oil".to_string(), Category::Pantry),
        ("canola oil".to_string(), Category::Pantry),
        ("coconut oil".to_string(), Category::Pantry),
        ("sesame oil".to_string(), Category::Pantry),
        ("canned tomatoes".to_string(), Category::Pantry),
        ("diced tomatoes".to_string(), Category::Pantry),
        ("crushed tomatoes".to_string(), Category::Pantry),
        ("tomato paste".to_string(), Category::Pantry),
        ("tomato sauce".to_string(), Category::Pantry),
        ("marinara sauce".to_string(), Category::Pantry),
        ("soy sauce".to_string(), Category::Pantry),
        ("worcestershire sauce".to_string(), Category::Pantry),
        ("hot sauce".to_string(), Category::Pantry),
        ("ketchup".to_string(), Category::Pantry),
        ("mustard".to_string(), Category::Pantry),
        ("dijon mustard".to_string(), Category::Pantry),
        ("mayonnaise".to_string(), Category::Pantry),
        ("vinegar".to_string(), Category::Pantry),
        ("white vinegar".to_string(), Category::Pantry),
        ("apple cider vinegar".to_string(), Category::Pantry),
        ("balsamic vinegar".to_string(), Category::Pantry),
        ("red wine vinegar".to_string(), Category::Pantry),
        ("sugar".to_string(), Category::Pantry),
        ("brown sugar".to_string(), Category::Pantry),
        ("powdered sugar".to_string(), Category::Pantry),
        ("honey".to_string(), Category::Pantry),
        ("maple syrup".to_string(), Category::Pantry),
        ("baking powder".to_string(), Category::Pantry),
        ("baking soda".to_string(), Category::Pantry),
        ("yeast".to_string(), Category::Pantry),
        ("vanilla extract".to_string(), Category::Pantry),
        ("cocoa powder".to_string(), Category::Pantry),
        ("chocolate chips".to_string(), Category::Pantry),
        ("peanut butter".to_string(), Category::Pantry),
        ("almond butter".to_string(), Category::Pantry),
        ("jam".to_string(), Category::Pantry),
        ("jelly".to_string(), Category::Pantry),
        ("salsa".to_string(), Category::Pantry),
        ("coconut milk".to_string(), Category::Pantry),
        ("canned coconut milk".to_string(), Category::Pantry),
        ("fish sauce".to_string(), Category::Pantry),
        ("oyster sauce".to_string(), Category::Pantry),
        ("hoisin sauce".to_string(), Category::Pantry),
        ("sriracha".to_string(), Category::Pantry),
        ("tahini".to_string(), Category::Pantry),
        ("beef bouillon".to_string(), Category::Pantry),
        ("chicken bouillon".to_string(), Category::Pantry),
        ("wine".to_string(), Category::Pantry),
        ("white wine".to_string(), Category::Pantry),
        ("red wine".to_string(), Category::Pantry),
        ("beer".to_string(), Category::Pantry),
        ("almonds".to_string(), Category::Pantry),
        ("walnuts".to_string(), Category::Pantry),
        ("pecans".to_string(), Category::Pantry),
        ("cashews".to_string(), Category::Pantry),
        ("peanuts".to_string(), Category::Pantry),
        ("pine nuts".to_string(), Category::Pantry),
        ("sunflower seeds".to_string(), Category::Pantry),
        ("sesame seeds".to_string(), Category::Pantry),
        ("cornstarch".to_string(), Category::Pantry),
        ("vegetable shortening".to_string(), Category::Pantry),
        ("lard".to_string(), Category::Pantry),
        // Spices
        ("salt".to_string(), Category::Spices),
        ("sea salt".to_string(), Category::Spices),
        ("kosher salt".to_string(), Category::Spices),
        ("black pepper".to_string(), Category::Spices),
        ("white pepper".to_string(), Category::Spices),
        ("red pepper flakes".to_string(), Category::Spices),
        ("cayenne pepper".to_string(), Category::Spices),
        ("paprika".to_string(), Category::Spices),
        ("smoked paprika".to_string(), Category::Spices),
        ("garlic powder".to_string(), Category::Spices),
        ("onion powder".to_string(), Category::Spices),
        ("cumin".to_string(), Category::Spices),
        ("coriander".to_string(), Category::Spices),
        ("turmeric".to_string(), Category::Spices),
        ("cinnamon".to_string(), Category::Spices),
        ("nutmeg".to_string(), Category::Spices),
        ("allspice".to_string(), Category::Spices),
        ("cloves".to_string(), Category::Spices),
        ("cardamom".to_string(), Category::Spices),
        ("ginger powder".to_string(), Category::Spices),
        ("dried ginger".to_string(), Category::Spices),
        ("oregano".to_string(), Category::Spices),
        ("dried oregano".to_string(), Category::Spices),
        ("basil".to_string(), Category::Spices),
        ("dried basil".to_string(), Category::Spices),
        ("thyme".to_string(), Category::Spices),
        ("dried thyme".to_string(), Category::Spices),
        ("rosemary".to_string(), Category::Spices),
        ("dried rosemary".to_string(), Category::Spices),
        ("bay leaves".to_string(), Category::Spices),
        ("parsley".to_string(), Category::Spices),
        ("dried parsley".to_string(), Category::Spices),
        ("fresh parsley".to_string(), Category::Spices),
        ("cilantro".to_string(), Category::Spices),
        ("fresh cilantro".to_string(), Category::Spices),
        ("dill".to_string(), Category::Spices),
        ("fresh dill".to_string(), Category::Spices),
        ("chives".to_string(), Category::Spices),
        ("sage".to_string(), Category::Spices),
        ("dried sage".to_string(), Category::Spices),
        ("tarragon".to_string(), Category::Spices),
        ("marjoram".to_string(), Category::Spices),
        ("chili powder".to_string(), Category::Spices),
        ("italian seasoning".to_string(), Category::Spices),
        ("taco seasoning".to_string(), Category::Spices),
        ("old bay".to_string(), Category::Spices),
        ("everything bagel seasoning".to_string(), Category::Spices),
        ("mustard seeds".to_string(), Category::Spices),
        ("fennel seeds".to_string(), Category::Spices),
        ("caraway seeds".to_string(), Category::Spices),
        ("star anise".to_string(), Category::Spices),
        ("saffron".to_string(), Category::Spices),
        ("vanilla bean".to_string(), Category::Spices),
        ("mint".to_string(), Category::Spices),
        ("fresh mint".to_string(), Category::Spices),
        ("lemongrass".to_string(), Category::Spices),
    ])
}
